### ISSUE TITLE
delimiter option

### ISSUE THREAD

**Issue by tj** [segment-boneyard/tableize#1]
`_` is sort of ambiguous but `.` is not valid without quoting so that's a little lame

**Comment by ianstormtaylor** [comment]
if its any help, for a similar problem in traits on `identify` calls on the API i've been thinking we should use ` `whitespace for the delimiter so that things like`'company.name'`just become`'company name'`

**Comment by ianstormtaylor** [comment]
oh wow, didnt read the quoting part haha. ignore this

**Comment by tj** [comment]
quoting is probably better than some other weird delimiter, they allow $ too but that's so ugly haha company$name "company.name", maybe dots are fine haha fuck it
